apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: caddy-namespace
data:
  Caddyfile: |
    {
        auto_https disable
    }

    :80 {
        reverse_proxy / {
            to backend-service-1.default.svc.cluster.local:8080
               backend-service-2.default.svc.cluster.local:8080
               backend-service-3.default.svc.cluster.local:8080

            health_path /health
            health_interval 10s
            health_timeout 2s
            lb_policy round_robin
        }

        respond /health 200
    }
