apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: caddy-replicaset
  namespace: caddy-namespace
  labels:
    app: caddy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.7.4 # Use the latest stable version
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy
              readOnly: true
            - name: caddy-data
              mountPath: /data
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
        - name: caddy-data
          emptyDir: {}
